language: python

python:
  - "2.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE="split_expenses.settings"
    - PYTHONPATH="/home/travis/build/susg/split-expenses"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.11 DB=postgres

install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - python manage.py test  


