# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 18:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, default=b'', max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('date_spent', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_createsd', models.DateField(blank=True, default=datetime.datetime.now)),
                ('user_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expensedetails',
            name='group_spent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split.GroupProfile'),
        ),
        migrations.AddField(
            model_name='expensedetails',
            name='spender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split.UserProfile'),
        ),
    ]
