# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseDetails',
            new_name='ExpenseDetail',
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='user_created',
            field=models.CharField(max_length=20),
        ),
    ]
