# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0002_auto_20180601_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='user_created',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='split.UserProfile'),
        ),
    ]
