# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0003_auto_20180601_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='members',
            field=models.ManyToManyField(related_name='members', to='split.UserProfile'),
        ),
    ]
