# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0004_groupprofile_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='split.UserProfile'),
        ),
    ]
