# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0005_auto_20180602_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='date_createsd',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='name',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
