# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0007_auto_20180703_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='total_expense',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_owe',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_owed',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='expensedetail',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
